name 'demo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures demo'
long_description 'Installs/Configures demo'
version '0.1.0'

depends 'apt', '= 2.3.8'
depends 'hhvm', '~> 0.6.0'
depends 'mysqld', '~> 1.0.3'
